version: '3'
services:
  crdb:
    image: cockroachdb/cockroach:v22.1.0
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8081:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
  16-bits-back-end:
    depends_on:
      - crdb
    image: "16bits/zero2hero-be:0.0.2"
    container_name: 16-bits-back-end
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default,cockroachdb
  16-bits-front-end:
    image: "16bits/zero2hero-fe:0.0.1"
    container_name: 16-bits-front-end
    ports:
      - "3000:3000"